import json
import logging
import os
import uuid
import datetime
import urllib.parse
import re
from flask import jsonify
import functions_framework
from google.cloud import bigquery
from google.cloud import storage

# Initialize logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize GCP clients
bq_client = bigquery.Client()
storage_client = storage.Client()

PROJECT_ID = os.environ.get("PROJECT_ID", bq_client.project)
DATASET_ID = "highlight_reel_analytics"
TABLE_ID = "jobs"
RAW_VIDEOS_BUCKET = f"{PROJECT_ID}-raw-videos"

def get_user_identity(request):
    """Extracts email from IAP headers and queries the BigQuery user_roles table."""
    email = request.headers.get("x-goog-authenticated-user-email", "")
    if email.startswith("accounts.google.com:"):
        email = email[20:]
    
    role = "admin" # Default role for unauthenticated / direct access
    if email:
        try:
            query = f"SELECT role FROM `{PROJECT_ID}.{DATASET_ID}.user_roles` WHERE email = @email LIMIT 1"
            job_config = bigquery.QueryJobConfig(
                query_parameters=[bigquery.ScalarQueryParameter("email", "STRING", email)]
            )
            results = list(bq_client.query(query, job_config=job_config).result())
            if results:
                role = results[0].role.lower()
        except Exception as e:
            logger.error(f"Error fetching role for {email}: {e}")
    
    return email, role

@functions_framework.http
def get_jobs(request):
    """HTTP Cloud Function to handle job queries and submissions."""
    headers = {}

    path = request.path.strip('/')
    parts = path.split('/') if path else []
    
    # If routed through the load balancer, strip the 'api' prefix
    if parts and parts[0] == "api":
        parts = parts[1:]
    
    # Identify user and role
    user_email, user_role = get_user_identity(request)

    if request.method == "GET":
        if len(parts) == 1 and parts[0] == "me":
            return (jsonify({"email": user_email, "role": user_role}), 200, headers)
        elif len(parts) == 1 and parts[0] == "users":
            if user_role != "admin":
                return (jsonify({"error": "Forbidden: Only admins can manage users"}), 403, headers)
            try:
                query = f"SELECT email, role FROM `{PROJECT_ID}.{DATASET_ID}.user_roles` ORDER BY email"
                results = bq_client.query(query).result()
                users = [{"email": row.email, "role": row.role} for row in results]
                return (jsonify({"users": users}), 200, headers)
            except Exception as e:
                logger.error(f"Error querying users: {e}")
                return (jsonify({"error": str(e)}), 500, headers)
        elif len(parts) == 1 and parts[0] == "settings":
            if user_role != "admin":
                return (jsonify({"error": "Forbidden: Only admins can view settings"}), 403, headers)
            try:
                query = f"SELECT key, value FROM `{PROJECT_ID}.{DATASET_ID}.app_settings`"
                results = bq_client.query(query).result()
                settings = {row.key: row.value for row in results}
                
                if "ai_model" not in settings: settings["ai_model"] = "gemini-3.6-flash"
                if "analyzer_persona" not in settings: settings["analyzer_persona"] = "You are a sports video analyst. You have been given the audio transcript of a sports game with timestamps for each phrase."
                if "producer_persona" not in settings: settings["producer_persona"] = "You are the Executive Producer of a sports highlight show. Your job is to review the following draft script and selected timestamps generated by the junior analyst."

                if settings.get("proxy_pass"):
                    settings["proxy_pass"] = "******"

                return (jsonify({"settings": settings}), 200, headers)
            except Exception as e:
                logger.error(f"Error querying settings: {e}")
                return (jsonify({"error": str(e)}), 500, headers)

        elif len(parts) == 1 and parts[0] == "storage":
            if user_role != "admin":
                return (jsonify({"error": "Forbidden: Only admins can view storage stats"}), 403, headers)
            
            try:
                buckets_to_check = [
                    RAW_VIDEOS_BUCKET,
                    f"{PROJECT_ID}-temp-processing",
                    f"{PROJECT_ID}-processed-highlights"
                ]
                
                storage_stats = []
                for b_name in buckets_to_check:
                    try:
                        bucket = storage_client.bucket(b_name)
                        blobs = list(bucket.list_blobs())
                        total_size = sum(b.size for b in blobs if b.size is not None)
                        file_count = len(blobs)
                        storage_stats.append({
                            "bucket": b_name,
                            "file_count": file_count,
                            "total_size_bytes": total_size
                        })
                    except Exception as b_err:
                        logger.error(f"Error reading bucket {b_name}: {b_err}")
                        storage_stats.append({
                            "bucket": b_name,
                            "file_count": 0,
                            "total_size_bytes": 0,
                            "error": str(b_err)
                        })
                
                return (jsonify({"storage": storage_stats}), 200, headers)
            except Exception as e:
                logger.error(f"Error fetching storage stats: {e}")
                return (jsonify({"error": str(e)}), 500, headers)

        elif len(parts) == 0:
            try:
                query = f"""
                    SELECT job_id, status, created_at, config, error_message
                    FROM `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}`
                    ORDER BY created_at DESC
                    LIMIT 50
                """
                query_job = bq_client.query(query)
                results = query_job.result()

                jobs = []
                for row in results:
                    jobs.append({
                        "id": row.job_id,
                        "status": row.status,
                        "created_at": row.created_at.isoformat() if row.created_at else None,
                        "config": row.config,
                        "error_message": row.get("error_message")
                    })

                return (jsonify({"jobs": jobs}), 200, headers)
            except Exception as e:
                logger.error(f"Error querying jobs: {e}")
                return (jsonify({"error": str(e)}), 500, headers)
        elif len(parts) == 2 and parts[1] == "video":
            job_id = parts[0]
            try:
                query = f"SELECT JSON_EXTRACT_SCALAR(config, '$.final_video_uri') AS final_video_uri FROM `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}` WHERE job_id = @job_id"
                job_config = bigquery.QueryJobConfig(query_parameters=[bigquery.ScalarQueryParameter("job_id", "STRING", job_id)])
                results = list(bq_client.query(query, job_config=job_config).result())
                
                if not results or not results[0].final_video_uri:
                    return (jsonify({"error": "Video not found"}), 404, headers)
                
                gcs_uri = results[0].final_video_uri
                if not gcs_uri.startswith("gs://"):
                    return (jsonify({"error": "Invalid video URI"}), 500, headers)
                
                uri_parts = gcs_uri[5:].split('/', 1)
                bucket_name = uri_parts[0]
                blob_name = uri_parts[1]
                
                bucket = storage_client.bucket(bucket_name)
                blob = bucket.blob(blob_name)
                
                import google.auth
                from google.auth.transport import requests
                credentials, project = google.auth.default()
                if not credentials.valid:
                    credentials.refresh(requests.Request())
                
                url = blob.generate_signed_url(
                    version="v4",
                    expiration=datetime.timedelta(minutes=15),
                    method="GET",
                    service_account_email=credentials.service_account_email,
                    access_token=credentials.token
                )
                return (jsonify({"url": url}), 200, headers)
            except Exception as e:
                logger.error(f"Error generating signed URL: {e}")
                return (jsonify({"error": str(e)}), 500, headers)

        elif len(parts) == 2 and parts[1] == "logs":
            job_id = parts[0]
            try:
                from google.cloud import logging as cloud_logging
                logging_client = cloud_logging.Client()
                
                # 1. Find any Cloud Run Job execution names associated with this job_id
                exec_filter = f'"{job_id}" AND resource.type="cloud_run_job"'
                exec_entries = logging_client.list_entries(filter_=exec_filter, order_by=cloud_logging.DESCENDING, max_results=50)
                
                execution_names = set()
                for entry in exec_entries:
                    if entry.labels and "run.googleapis.com/execution_name" in entry.labels:
                        execution_names.add(entry.labels["run.googleapis.com/execution_name"])
                
                # 2. Construct combined filter
                filter_conditions = [f'"{job_id}"']
                for exec_name in execution_names:
                    filter_conditions.append(f'labels."run.googleapis.com/execution_name"="{exec_name}"')
                
                combined_filter = f'({" OR ".join(filter_conditions)}) AND NOT logName:("run.googleapis.com/requests" OR "cloudaudit.googleapis.com")'
                
                # 3. Fetch all logs matching combined filter
                entries = logging_client.list_entries(filter_=combined_filter, order_by=cloud_logging.DESCENDING, max_results=200)
                
                logs = []
                for entry in entries:
                    if isinstance(entry.payload, str):
                        msg = entry.payload
                    elif isinstance(entry.payload, dict):
                        msg = json.dumps(entry.payload)
                    elif getattr(entry, 'text_payload', None):
                        msg = entry.text_payload
                    elif getattr(entry, 'json_payload', None):
                        msg = json.dumps(entry.json_payload)
                    elif getattr(entry, 'message', None):
                        msg = entry.message
                    else:
                        msg = str(entry)

                    logs.append({
                        "timestamp": entry.timestamp.isoformat() if entry.timestamp else "",
                        "severity": entry.severity or "INFO",
                        "message": msg
                    })
                return (jsonify({"logs": logs}), 200, headers)
            except Exception as e:
                logger.error(f"Error fetching logs for job {job_id}: {e}")
                return (jsonify({"error": str(e)}), 500, headers)

    elif request.method == "POST":
        if len(parts) == 1 and parts[0] == "users":
            if user_role != "admin":
                return (jsonify({"error": "Forbidden: Only admins can manage users"}), 403, headers)
            
            req_data = request.get_json()
            email = req_data.get("email")
            role = req_data.get("role")
            if not email or role not in ["admin", "user", "viewer"]:
                return (jsonify({"error": "Invalid payload"}), 400, headers)
            
            try:
                merge_query = f"""
                    MERGE `{PROJECT_ID}.{DATASET_ID}.user_roles` T
                    USING (SELECT @email as email, @role as role) S
                    ON T.email = S.email
                    WHEN MATCHED THEN
                      UPDATE SET role = S.role
                    WHEN NOT MATCHED THEN
                      INSERT (email, role) VALUES (S.email, S.role)
                """
                job_config = bigquery.QueryJobConfig(
                    query_parameters=[
                        bigquery.ScalarQueryParameter("email", "STRING", email),
                        bigquery.ScalarQueryParameter("role", "STRING", role)
                    ]
                )
                bq_client.query(merge_query, job_config=job_config).result()
                return (jsonify({"message": "User updated"}), 200, headers)
            except Exception as e:
                logger.error(f"Error updating user: {e}")
                return (jsonify({"error": str(e)}), 500, headers)

        elif len(parts) == 1 and parts[0] == "settings":
            if user_role != "admin":
                return (jsonify({"error": "Forbidden: Only admins can manage settings"}), 403, headers)
            req_data = request.get_json()
            if not req_data:
                return (jsonify({"error": "No payload"}), 400, headers)
            
            try:
                for key, value in req_data.items():
                    merge_query = f"""
                        MERGE `{PROJECT_ID}.{DATASET_ID}.app_settings` T
                        USING (SELECT @key as key, @value as value) S
                        ON T.key = S.key
                        WHEN MATCHED THEN
                          UPDATE SET value = S.value
                        WHEN NOT MATCHED THEN
                          INSERT (key, value) VALUES (S.key, S.value)
                    """
                    job_config = bigquery.QueryJobConfig(
                        query_parameters=[
                            bigquery.ScalarQueryParameter("key", "STRING", key),
                            bigquery.ScalarQueryParameter("value", "STRING", value)
                        ]
                    )
                    bq_client.query(merge_query, job_config=job_config).result()
                return (jsonify({"message": "Settings updated"}), 200, headers)
            except Exception as e:
                logger.error(f"Error updating settings: {e}")
                return (jsonify({"error": str(e)}), 500, headers)

        elif len(parts) == 2 and parts[1] == "restart":
            if user_role != "admin":
                return (jsonify({"error": "Forbidden: Only admins can restart jobs"}), 403, headers)
            
            job_id = parts[0]
            req_payload = request.get_json(silent=True) or {}
            mode = req_payload.get("mode", "smart" if req_payload.get("smart", True) else "full")
            
            try:
                query = f"SELECT config, status FROM `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}` WHERE job_id = @job_id LIMIT 1"
                job_config = bigquery.QueryJobConfig(
                    query_parameters=[bigquery.ScalarQueryParameter("job_id", "STRING", job_id)]
                )
                query_job = bq_client.query(query, job_config=job_config)
                results = list(query_job.result())
                if not results:
                    return (jsonify({"error": "Job not found"}), 404, headers)
                
                cfg = json.loads(results[0].config) if results[0].config else {}
                last_good_stage = cfg.get("last_good_stage")

                # Auto-discover GCS artifacts for existing legacy jobs created before stage persistence
                if mode == "smart" and not last_good_stage:
                    try:
                        temp_bucket = storage_client.bucket(f"{PROJECT_ID}-temp-processing")
                        blobs = list(temp_bucket.list_blobs(prefix=f"{job_id}/"))
                        blob_names = [b.name for b in blobs]
                        if f"{job_id}/subtitles.srt" in blob_names:
                            audio_uris = [f"gs://{PROJECT_ID}-temp-processing/{b}" for b in blob_names if "audio_" in b]
                            if audio_uris:
                                cfg["audioUris"] = audio_uris
                                cfg["srtUri"] = f"gs://{PROJECT_ID}-temp-processing/{job_id}/subtitles.srt"
                                cfg["last_good_stage"] = "AUDIO_GEN"
                                last_good_stage = "AUDIO_GEN"
                                logger.info(f"Discovered legacy GCS audio artifacts for existing job {job_id}. Resuming at AUDIO_GEN.")
                    except Exception as legacy_err:
                        logger.warning(f"Legacy artifact discovery skipped for job {job_id}: {legacy_err}")

                # If mode is smart and a previous good stage exists
                if mode == "smart" and last_good_stage:
                    from google.cloud import pubsub_v1
                    publisher = pubsub_v1.PublisherClient()
                    
                    if last_good_stage == "AUDIO_GEN" and cfg.get("audioUris") and cfg.get("srtUri"):
                        # Resume directly at RENDERING_VIDEO
                        from google.cloud import run_v2
                        update_query = f"UPDATE `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}` SET status = 'RENDERING_VIDEO', error_message = NULL WHERE job_id = @job_id"
                        bq_client.query(update_query, job_config=job_config).result()

                        render_message = cfg.copy()
                        render_message["jobId"] = job_id
                        render_message["audioUris"] = cfg.get("audioUris")
                        render_message["srtUri"] = cfg.get("srtUri")
                        render_message["videoUri"] = cfg.get("video_gcs_uri")
                        render_message["script"] = cfg.get("render_script") or cfg.get("final_script")

                        client = run_v2.JobsClient()
                        job_name = f"projects/{PROJECT_ID}/locations/us-central1/jobs/video-renderer-job"
                        overrides = run_v2.RunJobRequest.Overrides(
                            container_overrides=[
                                run_v2.RunJobRequest.Overrides.ContainerOverride(
                                    env=[run_v2.EnvVar(name="JOB_PAYLOAD", value=json.dumps(render_message))]
                                )
                            ]
                        )
                        client.run_job(request=run_v2.RunJobRequest(name=job_name, overrides=overrides))
                        return (jsonify({"message": "Resumed job from last good stage: Rendering Video", "jobId": job_id, "resumedStage": "RENDERING_VIDEO"}), 200, headers)

                    elif last_good_stage == "REVIEWING_SCRIPT" and cfg.get("final_script"):
                        # Resume directly at GENERATING_AUDIO
                        update_query = f"UPDATE `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}` SET status = 'GENERATING_AUDIO', error_message = NULL WHERE job_id = @job_id"
                        bq_client.query(update_query, job_config=job_config).result()

                        topic_path = publisher.topic_path(PROJECT_ID, "generate-audio")
                        audio_payload = cfg.copy()
                        audio_payload["jobId"] = job_id
                        audio_payload["script"] = cfg.get("final_script")
                        data = json.dumps(audio_payload).encode("utf-8")
                        publisher.publish(topic_path, data)
                        return (jsonify({"message": "Resumed job from last good stage: Generating Audio", "jobId": job_id, "resumedStage": "GENERATING_AUDIO"}), 200, headers)

                    elif last_good_stage == "ANALYZING_SCRIPT" and cfg.get("draft_script"):
                        # Resume directly at REVIEWING_SCRIPT
                        update_query = f"UPDATE `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}` SET status = 'REVIEWING_SCRIPT', error_message = NULL WHERE job_id = @job_id"
                        bq_client.query(update_query, job_config=job_config).result()

                        topic_path = publisher.topic_path(PROJECT_ID, "review-script")
                        review_payload = {
                            "jobId": job_id,
                            "script": cfg.get("draft_script"),
                            "original_payload": cfg
                        }
                        data = json.dumps(review_payload).encode("utf-8")
                        publisher.publish(topic_path, data)
                        return (jsonify({"message": "Resumed job from last good stage: Script Review", "jobId": job_id, "resumedStage": "REVIEWING_SCRIPT"}), 200, headers)

                # Fallback to Full Restart from beginning (PENDING)
                update_query = f"UPDATE `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}` SET status = 'PENDING', error_message = NULL WHERE job_id = @job_id"
                bq_client.query(update_query, job_config=job_config).result()
                
                bucket = storage_client.bucket(RAW_VIDEOS_BUCKET)
                try:
                    lock_blob = bucket.blob(f"locks/{job_id}.lock")
                    if lock_blob.exists():
                        lock_blob.delete()
                except Exception as e:
                    logger.warning(f"Could not delete lock file: {e}")

                blob = bucket.blob(f"{job_id}.job")
                blob.upload_from_string(json.dumps(cfg), content_type="application/json")
                
                return (jsonify({"message": "Restarted job from beginning (PENDING)", "jobId": job_id, "resumedStage": "PENDING"}), 200, headers)
            except Exception as e:
                logger.error(f"Error restarting job: {e}")
                return (jsonify({"error": str(e)}), 500, headers)

        elif len(parts) == 1 and parts[0] == "upload-url":
            if user_role == "viewer":
                return (jsonify({"error": "Forbidden: Viewers cannot upload videos"}), 403, headers)
            
            try:
                req_data = request.get_json(silent=True) or {}
                content_type = (req_data.get("contentType") or "video/mp4").lower()
                filename = (req_data.get("filename") or "").lower()
                
                allowed_mimes = {"video/mp4", "video/quicktime", "video/x-msvideo", "video/webm", "video/mkv", "video/avi"}
                allowed_exts = (".mp4", ".mov", ".avi", ".webm", ".mkv")
                
                if content_type not in allowed_mimes and not filename.endswith(allowed_exts):
                    return (jsonify({"error": "Invalid content type or file extension. Only video files (MP4, MOV, AVI, WEBM, MKV) are allowed."}), 400, headers)

                # Generate a temporary ID for the upload
                video_id = str(uuid.uuid4())
                bucket = storage_client.bucket(RAW_VIDEOS_BUCKET)
                blob = bucket.blob(f"uploads/{video_id}.mp4")
                
                import google.auth
                from google.auth.transport import requests
                credentials, project = google.auth.default()
                if not credentials.valid:
                    credentials.refresh(requests.Request())

                url = blob.generate_signed_url(
                    version="v4",
                    expiration=datetime.timedelta(minutes=30),
                    method="PUT",
                    content_type=content_type,
                    service_account_email=credentials.service_account_email,
                    access_token=credentials.token
                )
                
                gcs_uri = f"gs://{RAW_VIDEOS_BUCKET}/uploads/{video_id}.mp4"
                return (jsonify({"url": url, "video_gcs_uri": gcs_uri}), 200, headers)
            except Exception as e:
                logger.error(f"Error generating upload URL: {e}")
                return (jsonify({"error": str(e)}), 500, headers)

        elif len(parts) == 2 and parts[1] == "update":
            if user_role == "viewer":
                return (jsonify({"error": "Forbidden: Viewers cannot update jobs"}), 403, headers)
            
            job_id = parts[0]
            req_data = request.get_json() or {}
            
            def sanitize(text):
                if not text: return ""
                sanitized = re.sub(r'[^\w\s\-,.!]', '', str(text))
                return sanitized[:100]

            try:
                query = f"SELECT config FROM `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}` WHERE job_id = @job_id LIMIT 1"
                job_config = bigquery.QueryJobConfig(
                    query_parameters=[bigquery.ScalarQueryParameter("job_id", "STRING", job_id)]
                )
                results = list(bq_client.query(query, job_config=job_config).result())
                if not results:
                    return (jsonify({"error": "Job not found"}), 404, headers)
                
                existing_config = json.loads(results[0].config) if results[0].config else {}
                
                # Update allowed settings: Analysis Mode, Aspect Ratio, Dual Voices, Length, Music Track, Team Player Bias, Language, etc.
                editable_fields = ["analysisMode", "aspectRatio", "dualVoices", "length", "musicTrack", "teamPlayerBias", "language", "tone", "voice", "voice2"]
                for key in editable_fields:
                    if key in req_data:
                        if isinstance(req_data[key], bool):
                            existing_config[key] = req_data[key]
                        else:
                            existing_config[key] = sanitize(req_data[key])

                update_query = f"UPDATE `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}` SET config = PARSE_JSON(@config) WHERE job_id = @job_id"
                job_config_update = bigquery.QueryJobConfig(
                    query_parameters=[
                        bigquery.ScalarQueryParameter("config", "STRING", json.dumps(existing_config)),
                        bigquery.ScalarQueryParameter("job_id", "STRING", job_id)
                    ]
                )
                bq_client.query(update_query, job_config=job_config_update).result()
                return (jsonify({"message": "Job updated successfully", "config": existing_config}), 200, headers)
            except Exception as e:
                logger.error(f"Error updating job: {e}")
                return (jsonify({"error": str(e)}), 500, headers)

        elif len(parts) == 0:
            if user_role == "viewer":
                return (jsonify({"error": "Forbidden: Viewers cannot create jobs"}), 403, headers)
                
            req_data = request.get_json()
            if not req_data:
                return (jsonify({"error": "No JSON payload provided"}), 400, headers)

            def sanitize(text):
                if not text: return ""
                sanitized = re.sub(r'[^\w\s\-,.!]', '', str(text))
                return sanitized[:100]

            youtube_url = str(req_data.get("youtubeUrl", "")).strip()
            if youtube_url:
                parsed_url = urllib.parse.urlparse(youtube_url)
                if parsed_url.scheme not in ["http", "https"]:
                    return (jsonify({"error": "Invalid YouTube URL scheme. Must be http or https."}), 400, headers)
                allowed_domains = {"youtube.com", "www.youtube.com", "m.youtube.com", "youtu.be"}
                if parsed_url.netloc.lower() not in allowed_domains:
                    return (jsonify({"error": "Invalid YouTube URL domain. Only YouTube URLs are allowed."}), 400, headers)

            orig_filename = req_data.get("originalFileName") or req_data.get("filename")
            if not orig_filename and req_data.get("video_gcs_uri"):
                orig_filename = os.path.basename(req_data.get("video_gcs_uri"))
            if orig_filename:
                orig_filename = re.sub(r'\.[^/.]+$', '', str(orig_filename))

            job_id = str(uuid.uuid4())
            job_data = {
                "jobId": job_id,
                "originalFileName": sanitize(orig_filename),
                "language": sanitize(req_data.get("language", "en")),
                "video_gcs_uri": req_data.get("video_gcs_uri"),
                "youtubeUrl": youtube_url[:200],
                "tone": sanitize(req_data.get("tone")),
                "teamPlayerBias": sanitize(req_data.get("teamPlayerBias")),
                "musicTrack": sanitize(req_data.get("musicTrack")),
                "aspectRatio": sanitize(req_data.get("aspectRatio", "16:9")),
                "length": sanitize(req_data.get("length", "60")),
                "voice": sanitize(req_data.get("voice", "en-US-Journey-D")),
                "voice2": sanitize(req_data.get("voice2", "en-US-Journey-F")),
                "dualVoices": req_data.get("dualVoices", False),
                "analysisMode": sanitize(req_data.get("analysisMode", "video")),
                "userEmail": user_email
            }
            
            try:
                insert_query = f"""
                    INSERT INTO `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}` (job_id, status, created_at, config)
                    VALUES (@job_id, 'PENDING', @created_at, PARSE_JSON(@config))
                """
                job_config = bigquery.QueryJobConfig(
                    query_parameters=[
                        bigquery.ScalarQueryParameter("job_id", "STRING", job_id),
                        bigquery.ScalarQueryParameter("created_at", "TIMESTAMP", datetime.datetime.now(datetime.timezone.utc).isoformat()),
                        bigquery.ScalarQueryParameter("config", "STRING", json.dumps(job_data))
                    ]
                )
                bq_client.query(insert_query, job_config=job_config).result()
                
                # 2. Drop .job file into raw videos bucket to trigger Eventarc
                bucket = storage_client.bucket(RAW_VIDEOS_BUCKET)
                        
                blob = bucket.blob(f"{job_id}.job")
                blob.upload_from_string(json.dumps(job_data), content_type="application/json")
                
                return (jsonify({"message": "Job submitted successfully", "jobId": job_id}), 201, headers)
                
            except Exception as e:
                logger.error(f"Error handling POST: {e}")
                return (jsonify({"error": str(e)}), 500, headers)

    elif request.method == "DELETE":
        if user_role != "admin":
            return (jsonify({"error": "Forbidden: Only admins can delete jobs or users"}), 403, headers)
            
        if len(parts) == 2 and parts[0] == "users":
            email_to_delete = urllib.parse.unquote(parts[1])
            try:
                delete_query = f"DELETE FROM `{PROJECT_ID}.{DATASET_ID}.user_roles` WHERE email = @email"
                job_config = bigquery.QueryJobConfig(
                    query_parameters=[bigquery.ScalarQueryParameter("email", "STRING", email_to_delete)]
                )
                bq_client.query(delete_query, job_config=job_config).result()
                return (jsonify({"message": "User deleted", "email": email_to_delete}), 200, headers)
            except Exception as e:
                logger.error(f"Error deleting user: {e}")
                return (jsonify({"error": str(e)}), 500, headers)

        elif len(parts) == 1:
            job_id = parts[0]
            try:
                # Fetch job config to get video_gcs_uri before database deletion
                video_gcs_uri = None
                try:
                    select_query = f"SELECT config FROM `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}` WHERE job_id = @job_id LIMIT 1"
                    select_config = bigquery.QueryJobConfig(
                        query_parameters=[bigquery.ScalarQueryParameter("job_id", "STRING", job_id)]
                    )
                    results = list(bq_client.query(select_query, job_config=select_config).result())
                    if results and results[0].config:
                        cfg = json.loads(results[0].config)
                        video_gcs_uri = cfg.get("video_gcs_uri")
                except Exception as fetch_err:
                    logger.warning(f"Could not fetch config prior to job deletion: {fetch_err}")

                # Delete BigQuery database record
                delete_query = f"DELETE FROM `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}` WHERE job_id = @job_id"
                job_config = bigquery.QueryJobConfig(
                    query_parameters=[bigquery.ScalarQueryParameter("job_id", "STRING", job_id)]
                )
                bq_client.query(delete_query, job_config=job_config).result()
                
                # Delete raw uploaded video blob if referenced by video_gcs_uri
                if video_gcs_uri:
                    try:
                        parsed_uri = urllib.parse.urlparse(video_gcs_uri)
                        raw_bucket_name = parsed_uri.netloc
                        raw_blob_name = parsed_uri.path.lstrip('/')
                        if raw_bucket_name and raw_blob_name:
                            raw_blob = storage_client.bucket(raw_bucket_name).blob(raw_blob_name)
                            if raw_blob.exists():
                                raw_blob.delete()
                                logger.info(f"Deleted uploaded raw video {video_gcs_uri} for job {job_id}")
                    except Exception as raw_del_err:
                        logger.error(f"Failed to delete raw video {video_gcs_uri}: {raw_del_err}")

                # Delete all matching GCS Artifacts (.job, .lock, temp processing files, final video)
                buckets_to_clean = [
                    RAW_VIDEOS_BUCKET,
                    f"{PROJECT_ID}-temp-processing",
                    f"{PROJECT_ID}-processed-highlights"
                ]
                for b_name in buckets_to_clean:
                    try:
                        bucket = storage_client.bucket(b_name)
                        blobs = bucket.list_blobs()
                        for blob in blobs:
                            if job_id in blob.name:
                                try:
                                    blob.delete()
                                    logger.info(f"Deleted {blob.name} from {b_name} for deleted job {job_id}")
                                except Exception as inner_e:
                                    logger.error(f"Failed to delete blob {blob.name}: {inner_e}")
                    except Exception as e:
                        logger.error(f"Failed to clean bucket {b_name}: {e}")

                return (jsonify({"message": "Job and all associated artifacts deleted", "jobId": job_id}), 200, headers)
            except Exception as e:
                logger.error(f"Error deleting job: {e}")
                return (jsonify({"error": str(e)}), 500, headers)
        else:
            return (jsonify({"error": "Invalid delete path"}), 400, headers)

    else:
        return (jsonify({"error": "Method not allowed"}), 405, headers)
